.ruby-cache:
  before_script:
    - gem install bundler --version 2.2.5 --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}"
  cache:
    key:
      files:
        - timetraveler.gemspec
    paths:
      - vendor

default:
  image: ruby:2.6

include:
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - verify

before_script:
  - gem install bundler --version 2.1.4 --no-document
  - bundle install --jobs $(nproc) "${FLAGS[@]}"

build:
  stage: build
  script:
    - bundle exec rake build
  artifacts:
    paths:
      - pkg/*.gem
  extends: .ruby-cache

test:offline:
  stage: test
  needs: ["build"]
  script:
    - bundle exec rake spec:offline
  artifacts:
    when: always
    paths:
      - test-reports/rspec.xml
    reports:
      junit: test-reports/rspec.xml
  extends: .ruby-cache

test:online:
  stage: test
  needs: ["build"]
  script:
    - bundle exec rake spec:online
  only:
    refs:
      - master
  artifacts:
    when: always
    paths:
      - test-reports/rspec.xml
    reports:
      junit: test-reports/rspec.xml
  extends: .ruby-cache

yard:
  needs: ["build"]
  stage: verify
  script:
    - bundle exec rake yard
  extends: .ruby-cache

rubocop:
  needs: ["build"]
  stage: verify

  script:
    - bundle exec rake rubocop
  extends: .ruby-cache
