image: ruby:2.4.0

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - bundle install --path ./vendor
          - bundle exec rake build
          - bundle exec rake yard
          - bundle exec rake spec:offline

definitions:
  caches:
    bundler: ./vendor
